# Generated by Django 4.1.5 on 2023-03-02 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0006_rename_ingredient_product_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='small_description',
            field=models.CharField(default=1, max_length=50000),
            preserve_default=False,
        ),
    ]
