# Generated by Django 4.1.5 on 2023-03-03 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0007_product_small_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=2000)),
            ],
            options={
                'db_table': 'Ingredients',
            },
        ),
    ]
