# Generated by Django 4.1.5 on 2023-03-03 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0008_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredients',
            name='image',
            field=models.ImageField(default='abc.jpg', upload_to='Images'),
        ),
    ]
