# Generated by Django 4.1.5 on 2023-03-03 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0009_ingredients_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredients',
            name='sale_price',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
