# Generated by Django 4.1.5 on 2023-03-03 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0010_ingredients_sale_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredients',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
