# Generated by Django 4.1.5 on 2023-03-03 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AdminApp', '0011_ingredients_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('ingredients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.ingredients')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.userinformation')),
            ],
            options={
                'db_table': 'MyCart',
            },
        ),
    ]
