# Generated by Django 4.1.5 on 2023-03-04 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0011_ingredients_quantity'),
        ('UserApp', '0002_remove_mycart_ingredients_mycart_cakes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mycart',
            name='cakes',
        ),
        migrations.AddField(
            model_name='mycart',
            name='ingredients',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='AdminApp.ingredients'),
            preserve_default=False,
        ),
    ]
