# Generated by Django 4.1.5 on 2023-03-04 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0004_rename_ingredients_mycart_ingredient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mycart',
            old_name='ingredient',
            new_name='item_name',
        ),
        migrations.RenameField(
            model_name='mycart',
            old_name='qty',
            new_name='quantity',
        ),
    ]
