# Generated by Django 4.1.5 on 2023-03-04 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0005_rename_ingredient_mycart_item_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mycart',
            old_name='item_name',
            new_name='item',
        ),
    ]
