# Generated by Django 4.1.5 on 2023-03-04 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0006_rename_item_name_mycart_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mycart',
            old_name='item',
            new_name='items',
        ),
        migrations.RenameField(
            model_name='mycart',
            old_name='quantity',
            new_name='qty',
        ),
    ]
